# Generated by Django 2.0.6 on 2020-06-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('teacher_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField(null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=200, null=True)),
                ('token', models.CharField(default='', max_length=200, null=True)),
                ('time', models.CharField(default='', max_length=200, null=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('user_image1', models.CharField(max_length=500, null=True)),
                ('area_of_int', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperUpload',
            fields=[
                ('paper_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('paper_upload', models.FileField(upload_to='')),
                ('paper_description', models.CharField(default='', max_length=500)),
                ('author_name', models.CharField(default='', max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.FacultyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paperupload',
            name='role_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teacherapp.UserRole'),
        ),
        migrations.AddField(
            model_name='facultyinfo',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.UserRole'),
        ),
    ]
